laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ControllerProducto;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('productos', App\Http\Controllers\ControllerProducto::class);

Route::resource('detalles-usuario', App\Http\Controllers\HomeController::class)->middleware('auth');

Route::resource('carrito', App\Http\Controllers\ControllerCarrito::class);

Route::resource('favorito', App\Http\Controllers\ControllerFavorito::class);

Route::resource('resenas', App\Http\Controllers\ControllerResena::class);

Route::resource('pago', App\Http\Controllers\ControllerPedido::class);

Route::get('/ajax', 'App\Http\Controllers\ControllerProducto@ajax')->name('ajax');

Route::get('/ofertas', 'App\Http\Controllers\ControllerProducto@ofertas');

Route::get('/soporte', 'App\Http\Controllers\ControllerProducto@soporte');

Route::get('/destacados', 'App\Http\Controllers\ControllerProducto@destacados');

Route::get('/recomendados', 'App\Http\Controllers\ControllerProducto@recomendados');

Route::post('/sendmail',[
    'as' => 'sendmail',
    'uses' => 'App\Http\Controllers\ControllerPhpmailer@sendEmail'
  ]);

Auth::routes();

Route::resource('categoria', App\Http\Controllers\ControllerCategoria::class);


/*Route::group(['prefix' => 'electromes'], function(){
    
});

*/

laravel/app/Models/Producto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;

use Illuminate\Database\Eloquent\Model;

  

class Producto extends Model

{

    use HasFactory;

    protected $fillable = [

        'nombre', 'descripcion', 'precio', 'categoria', 'marca', 'memoria',
        'almacenamiento', 'bateria', 'pulgadas','procesador', 'tarjetaGrafica',
        'conectividad', 'tipoPantalla', 'tipoImpresion', 'anchura', 'altura', 
        'otros1', 'otros2', 'otros3', 'imagen1', 'imagen2', 'imagen3', 'imagen4', 
        'imagen5','valoracion', 'vendidos','esAdmin'

    ];

}

laravel/resources/views/productos/CRUD/index.blade.php
@extends('productos.CRUD.layout')

 

@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Laravel 8 CRUD</h2>

                <a class="btn btn-primary" href="/"> Back</a>
            </div>

        </div>

    </div>

   

    @if ($message = Session::get('success'))

        <div class="alert alert-success">

            <p>{{ $message }}</p>

        </div>

    @endif

   

    <table class="table table-bordered">

        <tr>

            <th>No</th>

            <th>Nombre</th>

            <th>Descripcion</th>

            <th>Categoria</th>

            <th>Precio</th>

            <th width="280px">Action</th>

        </tr>

        @foreach ($productos as $producto)

        <tr>

            <td>{{ ++$i }}</td>

            <td>{{ $producto->nombre }}</td>

            <td>{{ $producto->descripcion }}</td>
            
            <td>{{ $producto->categoria }}</td>
            
            <td>{{ $producto->precio }}</td>

            <td>

                <form action="{{ route('productos.destroy',$producto->id) }}" method="POST">

   

                    <a class="btn btn-info" href="{{ route('productos.show',$producto->id) }}">Show</a>

    

                    <a class="btn btn-primary" href="{{ route('productos.edit',$producto->id) }}">Edit</a>

   

                    @csrf

                    @method('DELETE')

      

                    <button type="submit" class="btn btn-danger">Delete</button>

                </form>

            </td>

        </tr>

        @endforeach

    </table>
    <a class="btn btn-success" href="{{ route('productos.create') }}"> Create New Producto</a>
  

    {!! $productos->links() !!}

      

@endsection

laravel/resources/views/productos/CRUD/layout.blade.php
<!DOCTYPE html>

<html>

<head>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">    
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
    <link rel="stylesheet" href="{{ asset('css/style.css') }}"/>

    <title>Electro Mes</title>
</head>

<body>

  

<div class="container">
    <br><br><br>
    @yield('content')

</div>

   

</body>

</html>

laravel/resources/views/productos/CRUD/show.blade.php
@extends('productos.CRUD.layout')

  

@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2> Show Producto</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('productos.index') }}"> Back</a>

            </div>

        </div>

    </div>

   

    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Nombre:</strong>

                {{ $producto->nombre }}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Descripcion:</strong>

                {{ $producto->descripcion }}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Categoria:</strong>

                {{ $producto->categoria }}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Precio:</strong>

                {{ $producto->precio }}

            </div>

        </div>

    </div>

@endsection