laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ControllerProducto;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('productos', App\Http\Controllers\ControllerProducto::class);

Route::resource('detalles-usuario', App\Http\Controllers\HomeController::class)->middleware('auth');

Route::resource('carrito', App\Http\Controllers\ControllerCarrito::class);

Route::resource('favorito', App\Http\Controllers\ControllerFavorito::class);

Route::resource('resenas', App\Http\Controllers\ControllerResena::class);

Route::resource('pago', App\Http\Controllers\ControllerPedido::class);

Route::get('/ajax', 'App\Http\Controllers\ControllerProducto@ajax')->name('ajax');

Route::get('/ofertas', 'App\Http\Controllers\ControllerProducto@ofertas');

Route::get('/soporte', 'App\Http\Controllers\ControllerProducto@soporte');

Route::get('/destacados', 'App\Http\Controllers\ControllerProducto@destacados');

Route::get('/recomendados', 'App\Http\Controllers\ControllerProducto@recomendados');

Route::post('/sendmail',[
    'as' => 'sendmail',
    'uses' => 'App\Http\Controllers\ControllerPhpmailer@sendEmail'
  ]);

Auth::routes();

Route::resource('categoria', App\Http\Controllers\ControllerCategoria::class);


/*Route::group(['prefix' => 'electromes'], function(){
    
});

*/

laravel/resources/views/productos/Includes/headers/header-links.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">    
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
    <link rel="stylesheet" href="{{ asset('css/style.css') }}"/>

    <title>Electro Mes</title>
</head>

        <script>
            $(document).ready(function(){
                $("#desplegableCategoriaOff").click(function(){
                    $("#desplegableCategoria").show("slow");
                });
                $("#cerrarDesplegableCat").click(function(){
                    $("#desplegableCategoria").hide("slow");
                });
            });   
            
            $(document).ready(function(){
                $("#lupaINPUT").click(function(){
                    $("#buscarINPUT").show();
                    $(".transFullPage").show(); 
                    $(".input-sm").show();    
                });

                $("#cerrarBuscarINPUT").click(function(){
                    $("#buscarINPUT").hide();
                    $(".transFullPage").hide();
                    $(".input-sm").hide();
                });

            });
        </script>
<body>  
           
            <div class="container-fluid">    
                <div class="row" style="position: fixed; width: 100%; background-color: white; z-index: 5; height: 70px;">

                    <!--Desplegable-->
                    <div class="col-2 col-sm-2 col-md-1 col-lg-1 col-xl-1" id="desplegableCategoriaOff">
                        <svg width="3.5em" height="3.5em" viewBox="0 0 16 16" class="bi bi-list cur mt-2"
                            style="cursor: pointer;" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
                        </svg>
                    </div>
                    
                    <div id="desplegableCategoria">
                        <div id="cerrarDesplegableCat"><i class="fa fa-close"></i></div>
                        @guest
                            @if (Route::has('login'))     
                                <h6 id="desplegableUser"><a href="{{ route('register') }}">{{ __('Inicar Sesión') }}</a></h6>
                            @endif

                            @else
                            <h6 id="desplegableUser">Bienvenid@, <a href="/detalles-usuario">{{ Auth::user()->name }}</a></h6>
                        @endguest
                        <hr>        

                        <div class="row ml-1">
                            <i class="material-icons iconoDesplegable col-1 col-sm-1 col-md-1 col-lg-1 col-xl-1">computer</i>
                            <a href="{{ route('categoria.show','ordenadores') }}"><h6 class="categoriasDesplegable col-11 col-sm-11 col-md-11 col-lg-10 col-xl-10">Ordenadores</h6></a>                     
                        </div>

                        <div class="row ml-1">
                            <i class="material-icons iconoDesplegable col-1 col-sm-1 col-md-1 col-lg-1 col-xl-1">laptop</i>
                            <a  href="{{ route('categoria.show','portatiles') }}"><h6 class="categoriasDesplegable col-11 col-sm-11 col-md-11 col-lg-10 col-xl-10">Portátiles</h6></a>                     
                        </div>
                        

                        <div class="row ml-1">
                            <i class="fas fa-mobile-alt iconoDesplegable col-1 col-sm-1 col-md-1 col-lg-1 col-xl-1" style="margin-top:1px; position:relative; left:5px;"></i>
                            <a  href="{{ route('categoria.show','telefonos') }}"><h6 class="categoriasDesplegable col-11 col-sm-11 col-md-11 col-lg-10 col-xl-10">Teléfonos</h6></a>                     
                        </div>

                        <div class="row ml-1">
                            <i class="fa fa-keyboard-o iconoDesplegable col-1 col-sm-1 col-md-1 col-lg-1 col-xl-1" style="margin-top:2px; position:relative; left:3px;"></i>
                            <a  href="{{ route('categoria.show','perifericos') }}"><h6 class="categoriasDesplegable col-11 col-sm-11 col-md-11 col-lg-10 col-xl-10">Periféricos</h6></a>                        
                        </div>

                        <div class="row ml-1">
                            <i class="material-icons iconoDesplegable col-1 col-sm-1 col-md-1 col-lg-1 col-xl-1">tv</i>
                            <a  href="{{ route('categoria.show','televisores') }}"><h6 class="categoriasDesplegable col-11 col-sm-11 col-md-11 col-lg-10 col-xl-10">Televisores</h6></a>
                        </div>

                        <div class="row ml-1">
                            <i class="fa fa-gamepad iconoDesplegable col-1 col-sm-1 col-md-1 col-lg-1 col-xl-1" style="margin-top:3px;"></i>
                            <a href="{{ route('categoria.show','consolas') }}"><h6 class="categoriasDesplegable col-11 col-sm-11 col-md-11 col-lg-10 col-xl-10">Consolas</h6></a>
                        </div>

                        <div class="row ml-1">
                            <i class="material-icons iconoDesplegable col-1 col-sm-1 col-md-1 col-lg-1 col-xl-1">print</i>
                            <a  href="{{ route('categoria.show','impresoras') }}"><h6 class="categoriasDesplegable col-11 col-sm-11 col-md-11 col-lg-10 col-xl-10">Impresoras</h6></a>
                        </div>

                        <div class="row ml-1">
                            <i class="fa fa-hdd-o iconoDesplegable col-1 col-sm-1 col-md-1 col-lg-1 col-xl-1" style="left:3px; position:relative"></i>
                            <a  href="{{ route('categoria.show','electrodomesticos') }}"><h6 class="categoriasDesplegable col-11 col-sm-10 col-md-11 col-lg-10 col-xl-10">Electrodomésticos</h6></a>
                        </div>

                        <hr>

                        <div class="row">   
                            <p style="margin-left:40px;"class="col-sm-10 col-md-10 col-lg-10 col-xl-10">ElectroMes<i class="far fa-copyright" style="font-size:10px; position:relative; bottom:5px; "></i></p>
                        </div>
                    </div>
                <div id="buscarINPUT">
                    <div class="row mt-3">
                        <div class="col-1 col-sm-1 col md-1"></div>
                        <div class="col-9 col-sm-9 md-9"></div>
                    
                        <i id="cerrarBuscarINPUT" class='far fa-window-close col-1 col-sm-1 col md-1'></i>
                    </div>
                </div>

laravel/resources/views/productos/Includes/headers/header.blade.php
                    
           
           <table class="table" id="datatable"></table>

<script>
    var datos = [];
    $(document).ready( function () {
        var table = $('#datatable').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url": "{{ route('api.customers.index') }}",
                "dataSrc": function(json){
                    for( var i=0, ien=json.data.length; i < ien ; i++){
                       datos.push(json.data[i]);
                    }
                    
                    return json.data;
                }
            },
            "columns": [
                
                { data: 'nombre', name: 'nombre', render:function(data, type, row){  
                    return "<a href='/productos/"+ row.id +"'><img style='width: 45px; height: 45px;' src='/producto/" + row.categoria + "/" + row.id + "/" + row.imagen1 + "'></a>"
                }},
                { data: 'categoria', name: 'categoria', render:function(data, type, row){
                    return "<div style='white-space: nowrap;overflow: hidden; width:165px'><a href='/productos/"+ row.id +"'>" + row.nombre + "</a></div>"
                }}
            ]
        });
    });
    $(document).ready(function(){
        $(".dataTables_filter label").css("color", "white");
        $("#datatable_length").hide();
        $("#dataTables_filter").hide();
        $("#datatable_info").hide();
        $("#datatable_paginate").hide();
        $("#datatable_paginate").hide();
        $(".sorting_asc").hide();
        $(".sorting").hide();
        $(".dataTable").hide();
    });
    function myFunction(x) {
        if (x.matches) { // If media query matches
            $(document).ready(function(){
                $(".input-sm").hide();
            });
        } else {
            $(document).ready(function(){
                $(".input-sm").show();
            });
        }
    }
    
    var x = window.matchMedia("(max-width: 767px)")
    myFunction(x) // Call listener function at run time
    x.addListener(myFunction) // Attach listener function on state changes

    $(document).ready(function(){
        $(".input-sm").focusin(function(){
            $(".dataTable").show();
        });
        $(".input-sm").focusout(function(){
            $(".dataTable").delay(10).fadeOut();
            
        }); 
    });
</script>

           <div class="transFullPage"></div>  
                    <!-- Buscador -->
                    <div class="col-3 col-sm-3 col-md-3 col-lg-3 col-xl-4 mt-3 d-none d-sm-none d-md-block"></div>

                    <!-- Ofertas XL -->
                    <div style="margin-left:51%; float: left; position: relative; top:-67px;"
                        class="d-none d-sm-none d-md-none d-lg-none d-xl-block">
                        <a href="/ofertas"><div class="row mt-4">
                            <i class='fas fa-bookmark' style='font-size:25px; margin-right:5px;'></i>
                            <h5 style="cursor: pointer;">Ofertas</h5>
                        </div></a>
                    </div>

                    <!-- Ofertas -->
                    <div class="d-block d-sm-block d-md-block d-lg-block d-xl-none mt-3"
                        style="margin-left: 71%; position: relative; bottom:58px;">
                        <a href="/ofertas"><i class='fas fa-bookmark' style='font-size:25px; margin-left: 10px; margin-top: 3px; color:black;'></i></a>
                    </div>

                      @guest

                    <!-- Carrito XL -->
                    <div style="margin-left:62%;  position: relative;top:-123px;"
                        class="d-none d-sm-none d-md-none d-lg-none d-xl-block">
                        <a href=""><div class="row mt-4">
                            <i class="fa fa-shopping-cart" style='font-size:25px; margin-right:5px; position:relative;'></i>    
                            <h5 style="cursor: pointer;" >Mi carrito</h5>
                        </div></a>
                    </div>

                     <!-- Carrito -->
                     <div class="d-block d-sm-block d-md-block d-lg-block d-xl-none mt-3"
                        style="margin-left: 60%;  position: relative; bottom: 106px; cursor:pointer;">
                        <a href=""><i class="fa fa-shopping-cart" style='font-size:25px; margin-left: 10px; margin-top: 3px; color:black;'></i></a>
                    </div>
                    
                @else

                    <!-- Carrito XL -->
                    <div style="margin-left:62%;  position: relative; top:-123px;"
                        class="d-none d-sm-none d-md-none d-lg-none d-xl-block">
                        <a href="{{ route('carrito.show',Auth::user()->id) }}"><div class="row mt-4">
                            <i class="fa fa-shopping-cart" style='font-size:25px; margin-right:5px; position:relative;'></i>    
                            <h5 style="cursor: pointer;" >Mi carrito</h5>
                        </div></a>
                    </div>


                    <!-- Carrito -->
                    <div class="d-block d-sm-block d-md-block d-lg-block d-xl-none mt-3"
                        style="margin-left: 60%;  position: relative; bottom: 106px; cursor:pointer;">
                        <a href="{{ route('carrito.show',Auth::user()->id) }}"><i class="fa fa-shopping-cart" style='font-size:25px; margin-left: 10px; margin-top: 3px; color:black;'></i></a>
                    </div>
                    
                @endguest   



                    <!-- Centro Soporte XL -->
                    <div style="margin-left:74%; float: left; position: relative;  bottom:180px;"
                        class="d-none d-sm-none d-md-none d-lg-none d-xl-block">
                        <a href="/soporte"><div class="row mt-4">
                            <i class='fa fa-question' style='font-size:25px; margin-right:5px;'></i>
                            <h5 style="cursor: pointer;">Soporte</h5>
                        </div></a>
                    </div>


                     <!-- Centro Soporte -->
                     <div class="d-block d-sm-block d-md-block d-lg-block d-xl-none mt-3"
                        style="margin-left: 80%; position: relative; bottom: 155px;">
                        <a href="/soporte"><i class='fa fa-question' style='font-size:25px; margin-left: 10px; margin-top: 3px; color:black;'></i></a>
                    </div>

               


                    <!-- Cuenta de Usuario XL -->
                    <div style="margin-left: 84%; float: right; position: relative; bottom:240px;"
                        class="d-none d-sm-none d-md-none d-lg-none d-xl-block">
                    
                    <!--Auteticaccion-->
                    @guest
                        <div class="row mt-4 ml-1"  >
                            <div class="dropdown" > 
                                <i class='fas fa-user-alt' style='font-size:25px; margin-right:5px; cursor: pointer; '></i>

                                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                                Mi cuenta<span class="caret"></span></button>



                                <ul class="dropdown-menu">
                                    <!--Logearse -->
                                    @if (Route::has('login'))     
                                        <li><a class="dropdown-item" href="{{ route('login') }}">{{ __('Iniciar Sesión') }}</a></li>
                                    @endif
                                    <!--Registrarse -->
                                    @if (Route::has('register'))  
                                        <li><a class="dropdown-item" href="{{ route('register') }}">{{ __('Registrarse') }}</a></li>
                                    @endif
                                </ul>
                            </div>
                        </div>

                        <!-- Usuario Logeado -->
                    @else
                        <div class="row mt-4 ml-1">
                            <div class="dropdown">
                                <i class='fas fa-user-alt' style='font-size:25px; margin-right:5px;'></i>

                                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                                {{ Auth::user()->name }}<span class="caret"></span></button>
                                
                                
                                <ul class="dropdown-menu">
                            
                                    <li><a class="dropdown-item" href="/detalles-usuario">{{ Auth::user()->name }}</li></a>
                                    <li><a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); 
                                        document.getElementById('logout-form').submit();">{{ __('Cerrar Sesión') }}</a>
                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                            @csrf
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    @endguest
                    </div>

                    <!-- Cuenta de Usuario -->
                    <div class="d-block d-sm-block d-md-block d-lg-block d-xl-none mt-3"
                        style="margin-left: 90%; position: relative; bottom:223px;">
                 
                        @guest
                        <div class="row ml-1 mt-4">
                            <div class="dropdown"> 
                                <i class='fas fa-user-alt dropdown-toggle' data-toggle="dropdown" 
                                style='font-size:25px; margin-left: 10px;'><span class="caret"></span></i>

                                <ul class="dropdown-menu">
                                    <!--Logearse -->
                                    @if (Route::has('login'))     
                                        <li><a class="dropdown-item" href="{{ route('login') }}">{{ __('Iniciar Sesión') }}</a></li>
                                    @endif
                                    <!--Registrarse -->
                                    @if (Route::has('register'))  
                                        <li><a class="dropdown-item" href="{{ route('register') }}">{{ __('Registrarse') }}</a></li>
                                    @endif
                                </ul>
                            </div>
                        </div>

                        <!-- Usuario Logeado -->
                    @else
                        <div class="row mt-4 ml-1">
                            <div class="dropdown">
                            <i class='fas fa-user-alt dropdown-toggle' data-toggle="dropdown" 
                                style='font-size:25px; margin-left: 10px;'><span class="caret"></span></i>
                                
                                
                                <ul class="dropdown-menu">
                            
                                    <li><a class="dropdown-item" href="/detalles-usuario">{{ Auth::user()->name }}</li></a>
                                    <li><a class="dropdown-item" href="{{ url('productos') }}" onclick="event.preventDefault(); 
                                        document.getElementById('logout-form').submit();">{{ __('Cerrar Sesión') }}</a>
                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                            @csrf
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    @endguest
                    </div>
                   

                    <!-- Icono lupa-->
                    <div class="d-sm-none d-md-none d-lg-none d-xl-none d-sm-block d-block mt-3"
                        style="margin-left: 51%; position: relative; bottom: 268px;">
                        <i class='fa fa-search' id="lupaINPUT" style='font-size:25px; cursor:pointer;'></i>   
                    </div>
                
                </div> 
        </div>